### ISSUE TITLE
Agreguen los links po oe!

### ISSUE THREAD

**Issue by luchosrock** [jfarriagada/noders-wiki#6]
Por último los de IMDB

**Comment by luis-fuentes** [comment]
y tu tienes las manos pintadas @luchosrock 💅

**Comment by luchosrock** [comment]
Rotten tomatoes, imdb o magnet link (torrent)??

**Comment by jfarriagada** [comment]
haha a la tarde agregare de [http://www.pelispedia.tv](url) y de paso buscaré una que ya las termine todas

**Comment by luchosrock** [comment]
pa eso armamos un json en firebase :tongue: y que este repo tenga un reproductor que se conecta a esa api

**Comment by jfarriagada** [comment]
desktop app with Electron rlz, sera mucho webeo ?

**Comment by jfarriagada** [comment]
o en vola meter la web en la desktop app
